### ISSUE TITLE
Error while saving Holiday or Vacation

### ISSUE THREAD

**Issue by mboremski** [mboremski/redmine_workload#1]
while trying to save an new national holiday I get an error response.
<my-PI>/redmine/wl_national_holiday/new -> Save

**Comment by mboremski** [comment]
Error log says:
```  
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
plugins/redmine_workload/app/controllers/wl_national_holiday_controller.rb:42:in `create'
```

**Comment by mboremski** [comment]
Managed to get a step forward while applying this:
https://stackoverflow.com/questions/17335329/activemodelforbiddenattributeserror-when-creating-new-user

**Comment by mboremski** [comment]
now getting this one while adding a vacation:
```
ActiveRecord::NotNullViolation (Mysql2::Error: Field 'user_id' doesn't have a default value: INSERT INTO `wl_user_vacations` VALUES ()):
plugins/redmine_workload/app/controllers/wl_user_vacations_controller.rb:38:in `create'
```

**Comment by mboremski** [comment]
@braini75, are you able to help?
